### ISSUE TITLE
Error while running `npm run package:discover` !

### ISSUE THREAD

**Issue by smrsan76** [os-js/osjs-xterm-application#4] opened 2018-11-08 23:22 UTC
I've just cloned the osjs v3 and install all of it's dependencies.

After that, I wanted to use this `osjs-xterm-application` package, therefore I installed it on osjs.

But I faced an error while running `npm run package:discover` to discover this package:

```
> @osjs/osjs@3.0.0-alpha.27 package:discover /home/smrsan/src/Clones/Web/OS.js
> osjs-cli package:discover

▶  package:discover Initialized timer...
[package:discover] › …  awaiting  Discovering packages
[package:discover] › …  watching  Using /home/smrsan/src/Clones/Web/OS.js/src/packages
[package:discover] › …  watching  Using /home/smrsan/src/Clones/Web/OS.js/node_modules
[package:discover] › …  awaiting  Flushing out old discoveries
{ [Error: EISDIR: illegal operation on a directory, unlink '/home/smrsan/src/Clones/Web/OS.js/dist/themes/fonts']
  errno: -21,
  code: 'EISDIR',
  syscall: 'unlink',
  path: '/home/smrsan/src/Clones/Web/OS.js/dist/themes/fonts' }
```

What's wrong with it ? and how can I fix it ?

**Comment by andersevenrud** [comment] 2018-11-08 23:39
Hm. I've never seen this before, actually.

I'm going to try to reproduce this tomorrow.

As of now, I've published a new release of `@osjs/cli`. So if you run `npm update @osjs/cli` and try again, it should work.

**Comment by andersevenrud** [comment] 2018-11-08 23:40
> So if you run `npm update @osjs/cli`

Inside the root OS.js installation.

**Comment by andersevenrud** [comment] 2018-11-08 23:40
Patch: https://github.com/os-js/osjs-cli/commit/664ea523d8db6213c9120904c6a06b38a6987e70

**Comment by smrsan76** [comment] 2018-11-08 23:44
It works in the new version.
but I think some other new errors generated !

```
  package:discover Initialized timer...
[package:discover] › …  awaiting  Discovering packages
[package:discover] › …  watching  Using /home/smrsan/src/Clones/Web/OS.js/src/packages
[package:discover] › …  watching  Using /home/smrsan/src/Clones/Web/OS.js/node_modules
[package:discover] › …  awaiting  Flushing out old discoveries
{ [Error: EISDIR: illegal operation on a directory, unlink '/home/smrsan/src/Clones/Web/OS.js/dist/themes/fonts']
  errno: -21,
  code: 'EISDIR',
  syscall: 'unlink',
  path: '/home/smrsan/src/Clones/Web/OS.js/dist/themes/fonts' }
{ [Error: EISDIR: illegal operation on a directory, unlink '/home/smrsan/src/Clones/Web/OS.js/dist/themes/sounds']
  errno: -21,
  code: 'EISDIR',
  syscall: 'unlink',
  path: '/home/smrsan/src/Clones/Web/OS.js/dist/themes/sounds' }
{ [Error: EISDIR: illegal operation on a directory, unlink '/home/smrsan/src/Clones/Web/OS.js/dist/themes/icons']
  errno: -21,
  code: 'EISDIR',
  syscall: 'unlink',
  path: '/home/smrsan/src/Clones/Web/OS.js/dist/themes/icons' }
{ [Error: EISDIR: illegal operation on a directory, unlink '/home/smrsan/src/Clones/Web/OS.js/dist/themes/styles']
  errno: -21,
  code: 'EISDIR',
  syscall: 'unlink',
  path: '/home/smrsan/src/Clones/Web/OS.js/dist/themes/styles' }
{ [Error: EISDIR: illegal operation on a directory, unlink '/home/smrsan/src/Clones/Web/OS.js/dist/themes/wallpapers']
  errno: -21,
  code: 'EISDIR',
  syscall: 'unlink',
  path: '/home/smrsan/src/Clones/Web/OS.js/dist/themes/wallpapers' }
[package:discover] › …  awaiting  Discovering packages
[package:discover] › ✔  success   12 package(s) discovered.
[package:discover] › ℹ  info      Discovered @osjs/calculator-application as Calculator
[package:discover] › ℹ  info      Discovered @osjs/draw-application as Draw
[package:discover] › ℹ  info      Discovered @osjs/filemanager-application as FileManager
[package:discover] › ℹ  info      Discovered @osjs/freedesktop-sounds as FreedesktopSounds
[package:discover] › ℹ  info      Discovered @osjs/gnome-icons as Gnome
[package:discover] › ℹ  info      Discovered @osjs/htmlviewer-application as HTMLViewer
[package:discover] › ℹ  info      Discovered @osjs/musicplayer-application as MusicPlayer
[package:discover] › ℹ  info      Discovered @osjs/preview-application as Preview
[package:discover] › ℹ  info      Discovered @osjs/settings-application as Settings
[package:discover] › ℹ  info      Discovered @osjs/standard-theme as Standard
[package:discover] › ℹ  info      Discovered @osjs/textpad-application as Textpad
[package:discover] › ℹ  info      Discovered @osjs/xterm-application as Xterm
◼  package:discover Timer run for: 424ms
```

What's the meaning of these errors alongside the success message ?!

**Comment by andersevenrud** [comment] 2018-11-08 23:45
The patch I made made it so that the command does not fail, it just logs the errors.

I'm not exactly sure what those errors mean yet.

Did you do *anything* except the standard installation guide ?

**Comment by smrsan76** [comment] 2018-11-08 23:48
> Did you do anything except the standard installation guide ?

Yes, I did...

**Comment by andersevenrud** [comment] 2018-11-08 23:48
> Yes, I did...

Could you elaborate ?

Because if you did something inside the `dist/` directory this might explain this.

**Comment by smrsan76** [comment] 2018-11-08 23:53
I've just done this instruction to install os.js and it's third-party package:

1. `git clone git@github.com:os-js/OS.js.git`
2. `git checkout v3`
3. `npm i`
4. `npm i -S @osjs/xterm-application`
5. `npm run package:discover`
6. `npm run build`
7. `npm run serve`

and now it seems to be a preset localhost password here ...

Where should I find it to make use of xterm-application ?

**Comment by andersevenrud** [comment] 2018-11-08 23:57
Ok. I'll investegate that tomorrow -- I failed to reproduce this here locally right now.

> and now it seems to be a preset localhost password here ...

As is mentioned here https://github.com/os-js/osjs-xterm-application/blob/master/README.md

---

> **Note that it will log into a shell with the username you are logged in as.**
> If you want to change this behavior, you can add this to your `src/server/config.js` file in the OS.js distribution:

```
{
  xterm: {
    // You can also set this as a string to force a username
    login: false
  }
}
```

---

By default OS.js does not use any authentication and logs in using a "demo" account.

See https://github.com/os-js/OS.js/blob/v3/src/client/config.js#L39

Ref:

* https://manual.os-js.org/v3/config/#client
* https://manual.os-js.org/v3/guide/auth/

**Comment by andersevenrud** [comment] 2018-11-08 23:58
I'm closing this issue because the main problem belongs in https://github.com/os-js/osjs-cli and the current question is off-topic.

**Closed as completed by andersevenrud** 2018-11-08 23:58 UTC
Labels: question

**Comment by andersevenrud** [comment] 2018-11-09 00:02
Just to elaborate:

The Xterm application just opens a shell on the server you deployed OS.js on. After that it will make a SSH session with a username -- which by default is grabbed from the OS.js user ("demo" if no customization is done).

If you set the login option to `false` it will open a shell on the user that runs the OS.js server. If you set it as a string, you will be asked the password of that user on the host system.

**Comment by andersevenrud** [comment] 2018-11-09 00:04
I've created an issue on the original topic here: https://github.com/os-js/osjs-cli/issues/5

**Comment by andersevenrud** [comment] 2018-11-09 00:16
This also made me think that adding an option to prompt for which user to login as would be a nice option:

New issue: https://github.com/os-js/osjs-xterm-application/issues/5
